//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisasterReliefFund.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disaster
    {
        public int DisasterID { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Location { get; set; }
        public string Aid_Type { get; set; }
    
        public virtual MonetaryDonation MonetaryDonation { get; set; }
        public virtual GoodsDonation GoodsDonation { get; set; }
    }
}
