//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisasterReliefFund.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Disaster_Relief_FoundationEntities1 : DbContext
    {
        public Disaster_Relief_FoundationEntities1()
            : base("name=Disaster_Relief_FoundationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Disaster> Disasters { get; set; }
        public virtual DbSet<GoodsDonation> GoodsDonations { get; set; }
        public virtual DbSet<MonetaryDonation> MonetaryDonations { get; set; }
    }
}
